import { dailyIndex } from '@/utils/daily';

// A piece of relationship advice each day: short, practical and for any couple.

export const COUPLE_TIPS: string[] = [
    'Pregúntale cómo le fue hoy y escucha la respuesta completa, sin mirar el teléfono.',
    'Di «gracias» por algo pequeño que tu pareja hace siempre y das por sentado.',
    'Cuando discutan, hablen del problema, no de la persona. «Me molestó esto» en vez de «tú siempre…».',
    'Planeen algo juntos para esta semana, aunque sea un paseo corto.',
    'Un mensaje a mitad del día diciendo que piensas en tu pareja cambia su tarde.',
    'Antes de responder en una discusión, repite con tus palabras lo que entendiste.',
    'Recuerden juntos cómo se conocieron. Revivir los comienzos une.',
    'Pide lo que necesitas de forma clara. Nadie adivina el pensamiento.',
    'Pide perdón sin «pero». Una disculpa con excusas no es disculpa.',
    'Dense un abrazo largo, de al menos veinte segundos.',
    'Cocinen algo juntos hoy, aunque sea sencillo.',
    'Celebra un logro de tu pareja como si fuera tuyo.',
    'Respeten el espacio propio: tener momentos a solas también cuida la relación.',
    'No se vayan a dormir con un enojo grande sin al menos acordar hablarlo mañana.',
    'Hagan una lista de sueños compartidos y elijan uno para empezar a cumplir.',
    'Deja una nota escrita a mano en un lugar donde tu pareja la encuentre.',
    'Pregúntale: «¿Hay algo que pueda hacer para que tu semana sea más fácil?».',
    'Repartan las tareas de la casa de forma que ambos sientan que es justo.',
    'Escucha para entender, no para responder.',
    'Hablen de dinero con calma y sin culpas. Los acuerdos claros evitan peleas.',
    'Presta atención a cómo tu pareja expresa cariño: palabras, gestos, tiempo, detalles o contacto.',
    'Salgan de la rutina: prueben un lugar o una actividad nueva juntos.',
    'Cuando algo te moleste, dilo pronto y con calma. Lo que se acumula explota.',
    'Apaguen las pantallas durante la cena y conversen.',
    'Haz un cumplido sincero y específico, no genérico.',
    'Pregunten qué recuerdo feliz tiene cada uno de este año.',
    'Una buena relación también se ríe. Busquen algo que les dé risa juntos.',
    'Respeta a su familia y amistades aunque no siempre coincidas con ellos.',
    'No compares tu relación con la de otros ni con lo que muestran las redes.',
    'Si la discusión sube de tono, pidan una pausa de veinte minutos y retómenla después.',
    'Recuerda fechas importantes para tu pareja, no solo el aniversario.',
    'Pregúntale qué le preocupa últimamente, y solo escucha.',
    'Tómense de la mano al caminar. Los gestos pequeños mantienen la cercanía.',
    'Hagan juntos algo por otros: ayudar une.',
    'Cumple lo que prometes, aunque sea algo chico. La confianza se construye así.',
    'Dile algo que admiras de su forma de ser.',
    'Acepten que hay temas en los que nunca estarán de acuerdo, y aprendan a convivir con eso.',
    'Planeen una cita como al principio: con ganas, sin prisa y sin hablar de pendientes.',
    'Si tu pareja tuvo un mal día, pregunta si quiere consejos o solo ser escuchada.',
    'Aprendan algo nuevo juntos: un idioma, un baile, una receta.',
    'Revisen juntos fotos antiguas y cuenten qué sentían en ese momento.',
    'Ofrece ayuda antes de que te la pidan.',
    'Hablen de sus metas personales y apóyense en ellas.',
    'Las bromas que hieren no son bromas. Cuida el tono.',
    'Agradece también el esfuerzo, no solo el resultado.',
    'Hagan un ritual propio: un café juntos, un paseo, una serie de los domingos.',
    'Cuando te equivoques, reconócelo rápido. Ahorra días de tensión.',
    'Pregúntale qué necesita más de ti en esta etapa.',
    'Sorprende sin motivo: los detalles fuera de fecha valen doble.',
    'No uses el silencio como castigo. Di que necesitas tiempo y cuándo volverás a hablar.',
    'Mírense a los ojos al hablar de algo importante.',
    'Recuerda que están en el mismo equipo, incluso cuando discuten.',
    'Hagan juntos una lista de lo que les gusta de su vida en común.',
    'Respeta sus tiempos: no todos procesan las emociones al mismo ritmo.',
    'Dile «te quiero» en un momento cualquiera, no solo al despedirse.',
    'Cuiden también su vida íntima: hablen de lo que a cada uno le gusta, sin vergüenza.',
    'Pidan ayuda profesional si lo necesitan. Ir a terapia de pareja es una forma de cuidarse.',
    'Terminen el día contándose algo bueno que les haya pasado.',
];

/** Today's tip. */
export function coupleTipOfTheDay(date: Date): string
{
    return COUPLE_TIPS[dailyIndex(date, COUPLE_TIPS.length, 'coupleTips')];
}
